USE [master]
GO
/****** Object:  Database [DDLAutomationProcess]    Script Date: 05-09-2024 09:13:23 ******/
CREATE DATABASE [DDLAutomationProcess]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DDLAutomationProcess', FILENAME = N'C:\Users\VenkateswaraoMokka\AppData\Local\Microsoft\VisualStudio\SSDT\DbUpForDML\DDLAutomationProcess.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DDLAutomationProcess_log', FILENAME = N'C:\Users\VenkateswaraoMokka\AppData\Local\Microsoft\VisualStudio\SSDT\DbUpForDML\DDLAutomationProcess.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DDLAutomationProcess] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DDLAutomationProcess].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DDLAutomationProcess] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [DDLAutomationProcess] SET ANSI_NULLS ON 
GO
ALTER DATABASE [DDLAutomationProcess] SET ANSI_PADDING ON 
GO
ALTER DATABASE [DDLAutomationProcess] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [DDLAutomationProcess] SET ARITHABORT OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DDLAutomationProcess] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DDLAutomationProcess] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [DDLAutomationProcess] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DDLAutomationProcess] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DDLAutomationProcess] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [DDLAutomationProcess] SET  MULTI_USER 
GO
ALTER DATABASE [DDLAutomationProcess] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DDLAutomationProcess] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DDLAutomationProcess] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DDLAutomationProcess] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DDLAutomationProcess] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DDLAutomationProcess] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [DDLAutomationProcess] SET QUERY_STORE = OFF
GO
USE [DDLAutomationProcess]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 05-09-2024 09:13:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AgeType]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AgeType](
	[AgeTypeID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_AgeType] PRIMARY KEY CLUSTERED 
(
	[AgeTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetRoleClaims]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetRoleClaims](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RoleId] [nvarchar](450) NOT NULL,
	[ClaimType] [nvarchar](max) NULL,
	[ClaimValue] [nvarchar](max) NULL,
 CONSTRAINT [PK_AspNetRoleClaims] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetRoles]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetRoles](
	[Id] [nvarchar](450) NOT NULL,
	[Discriminator] [nvarchar](21) NOT NULL,
	[Description] [nvarchar](max) NULL,
	[CreatedDate] [datetime2](7) NULL,
	[IPAddress] [nvarchar](max) NULL,
	[Name] [nvarchar](256) NULL,
	[NormalizedName] [nvarchar](256) NULL,
	[ConcurrencyStamp] [nvarchar](max) NULL,
 CONSTRAINT [PK_AspNetRoles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserClaims]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserClaims](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [nvarchar](450) NOT NULL,
	[ClaimType] [nvarchar](max) NULL,
	[ClaimValue] [nvarchar](max) NULL,
 CONSTRAINT [PK_AspNetUserClaims] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserLogins]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserLogins](
	[LoginProvider] [nvarchar](450) NOT NULL,
	[ProviderKey] [nvarchar](450) NOT NULL,
	[ProviderDisplayName] [nvarchar](max) NULL,
	[UserId] [nvarchar](450) NOT NULL,
 CONSTRAINT [PK_AspNetUserLogins] PRIMARY KEY CLUSTERED 
(
	[LoginProvider] ASC,
	[ProviderKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserRoles]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserRoles](
	[UserId] [nvarchar](450) NOT NULL,
	[RoleId] [nvarchar](450) NOT NULL,
 CONSTRAINT [PK_AspNetUserRoles] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUsers]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUsers](
	[Id] [nvarchar](450) NOT NULL,
	[Discriminator] [nvarchar](21) NOT NULL,
	[UserId] [int] NULL,
	[Name] [nvarchar](max) NULL,
	[CreatedDate] [datetime2](7) NULL,
	[IsActive] [bit] NULL,
	[UserName] [nvarchar](256) NULL,
	[NormalizedUserName] [nvarchar](256) NULL,
	[Email] [nvarchar](256) NULL,
	[NormalizedEmail] [nvarchar](256) NULL,
	[EmailConfirmed] [bit] NOT NULL,
	[PasswordHash] [nvarchar](max) NULL,
	[SecurityStamp] [nvarchar](max) NULL,
	[ConcurrencyStamp] [nvarchar](max) NULL,
	[PhoneNumber] [nvarchar](max) NULL,
	[PhoneNumberConfirmed] [bit] NOT NULL,
	[TwoFactorEnabled] [bit] NOT NULL,
	[LockoutEnd] [datetimeoffset](7) NULL,
	[LockoutEnabled] [bit] NOT NULL,
	[AccessFailedCount] [int] NOT NULL,
 CONSTRAINT [PK_AspNetUsers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AspNetUserTokens]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AspNetUserTokens](
	[UserId] [nvarchar](450) NOT NULL,
	[LoginProvider] [nvarchar](450) NOT NULL,
	[Name] [nvarchar](450) NOT NULL,
	[Value] [nvarchar](max) NULL,
 CONSTRAINT [PK_AspNetUserTokens] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC,
	[LoginProvider] ASC,
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BloodGroup]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BloodGroup](
	[BloodGroupID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_BloodGroup] PRIMARY KEY CLUSTERED 
(
	[BloodGroupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DaywiseSchedule]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DaywiseSchedule](
	[DayID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_Day] PRIMARY KEY CLUSTERED 
(
	[DayID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Department]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Department](
	[DepartmentID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Department] PRIMARY KEY CLUSTERED 
(
	[DepartmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DepartmentDayUnitMapping]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DepartmentDayUnitMapping](
	[DepartmentDayUnitMappingID] [int] IDENTITY(1,1) NOT NULL,
	[DepartmentID] [int] NOT NULL,
	[DayID] [int] NOT NULL,
	[UnitID] [int] NOT NULL,
 CONSTRAINT [PK_DepartmentDayUnitMapping] PRIMARY KEY CLUSTERED 
(
	[DepartmentDayUnitMappingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[District]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[District](
	[DistrictID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[StateID] [int] NOT NULL,
 CONSTRAINT [PK_District] PRIMARY KEY CLUSTERED 
(
	[DistrictID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Doctor]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Doctor](
	[DoctorID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Doctor] PRIMARY KEY CLUSTERED 
(
	[DoctorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FeeType]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FeeType](
	[FeeTypeID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_FeeType] PRIMARY KEY CLUSTERED 
(
	[FeeTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Gender]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Gender](
	[GenderID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Gender] PRIMARY KEY CLUSTERED 
(
	[GenderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IDProofType]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IDProofType](
	[IDProofTypeID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_IDProofType] PRIMARY KEY CLUSTERED 
(
	[IDProofTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Mandal]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Mandal](
	[MandalID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[DistrictID] [int] NOT NULL,
 CONSTRAINT [PK_Mandal] PRIMARY KEY CLUSTERED 
(
	[MandalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MaritalStatus]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MaritalStatus](
	[MaritalStatusID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MaritalStatus] PRIMARY KEY CLUSTERED 
(
	[MaritalStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OPRegistration]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OPRegistration](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PatientID] [int] NOT NULL,
	[OPID] [nvarchar](20) NOT NULL,
	[VisitDate] [datetime2](7) NOT NULL,
	[IsMlcCase] [bit] NULL,
	[IsEmergencyCase] [bit] NULL,
	[DepartmentID] [int] NULL,
	[DoctorID] [int] NULL,
	[SpecialityID] [int] NULL,
	[FeeTypeID] [int] NULL,
	[ReferredBy] [nvarchar](50) NOT NULL,
	[CreatedDate] [datetime2](7) NULL,
	[IsActive] [bit] NOT NULL,
 CONSTRAINT [PK_OPRegistration] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Patient]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Patient](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[UHID] [nvarchar](20) NOT NULL,
	[AadhaarNo] [bigint] NULL,
	[GenderID] [int] NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[MiddleName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[FatherName] [nvarchar](50) NOT NULL,
	[HusbandName] [nvarchar](50) NULL,
	[PrefixID] [int] NOT NULL,
	[MaritalStatusID] [int] NOT NULL,
	[Age] [int] NOT NULL,
	[AgeTypeID] [int] NOT NULL,
	[DOB] [datetime2](7) NULL,
	[MobileNumber] [bigint] NULL,
	[AlternateMobileNumber] [bigint] NULL,
	[Email] [nvarchar](100) NULL,
	[ReligionID] [int] NULL,
	[Caste] [nvarchar](50) NULL,
	[BloodGroupID] [int] NULL,
	[IDProofTypeID] [int] NULL,
	[IDProof] [nvarchar](50) NULL,
	[AbhaNo] [bigint] NULL,
	[PatientTypeID] [int] NULL,
	[VillageID] [int] NULL,
	[CreatedDate] [datetime2](7) NULL,
 CONSTRAINT [PK_Patient] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PatientAddress]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PatientAddress](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PatientID] [int] NOT NULL,
	[Village] [nvarchar](100) NOT NULL,
	[Mandal] [nvarchar](100) NOT NULL,
	[District] [nvarchar](100) NOT NULL,
	[State] [nvarchar](100) NOT NULL,
	[PinCode] [int] NOT NULL,
	[CreatedDate] [datetime2](7) NULL,
 CONSTRAINT [PK_PatientAddress] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PatientType]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PatientType](
	[PatientTypeID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_PatientType] PRIMARY KEY CLUSTERED 
(
	[PatientTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Prefix]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Prefix](
	[PrefixID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[GenderID] [int] NULL,
 CONSTRAINT [PK_Prefix] PRIMARY KEY CLUSTERED 
(
	[PrefixID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Religion]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Religion](
	[ReligionID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Religion] PRIMARY KEY CLUSTERED 
(
	[ReligionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Speciality]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Speciality](
	[SpecialityID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Speciality] PRIMARY KEY CLUSTERED 
(
	[SpecialityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[State]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[State](
	[StateID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_State] PRIMARY KEY CLUSTERED 
(
	[StateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Unit]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Unit](
	[UnitID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Unit] PRIMARY KEY CLUSTERED 
(
	[UnitID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UnitDoctorMapping]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UnitDoctorMapping](
	[UnitDoctorMappingID] [int] IDENTITY(1,1) NOT NULL,
	[UnitID] [int] NOT NULL,
	[DoctorID] [int] NOT NULL,
 CONSTRAINT [PK_UnitDoctorMapping] PRIMARY KEY CLUSTERED 
(
	[UnitDoctorMappingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Village]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Village](
	[VillageID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[MandalID] [int] NOT NULL,
	[Pincode] [int] NOT NULL,
 CONSTRAINT [PK_Village] PRIMARY KEY CLUSTERED 
(
	[VillageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_AspNetRoleClaims_RoleId]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_AspNetRoleClaims_RoleId] ON [dbo].[AspNetRoleClaims]
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [RoleNameIndex]    Script Date: 05-09-2024 09:13:24 ******/
CREATE UNIQUE NONCLUSTERED INDEX [RoleNameIndex] ON [dbo].[AspNetRoles]
(
	[NormalizedName] ASC
)
WHERE ([NormalizedName] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_AspNetUserClaims_UserId]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_AspNetUserClaims_UserId] ON [dbo].[AspNetUserClaims]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_AspNetUserLogins_UserId]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_AspNetUserLogins_UserId] ON [dbo].[AspNetUserLogins]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_AspNetUserRoles_RoleId]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_AspNetUserRoles_RoleId] ON [dbo].[AspNetUserRoles]
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [EmailIndex]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [EmailIndex] ON [dbo].[AspNetUsers]
(
	[NormalizedEmail] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [UserNameIndex]    Script Date: 05-09-2024 09:13:24 ******/
CREATE UNIQUE NONCLUSTERED INDEX [UserNameIndex] ON [dbo].[AspNetUsers]
(
	[NormalizedUserName] ASC
)
WHERE ([NormalizedUserName] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DepartmentDayUnitMapping_DayID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_DepartmentDayUnitMapping_DayID] ON [dbo].[DepartmentDayUnitMapping]
(
	[DayID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DepartmentDayUnitMapping_DepartmentID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_DepartmentDayUnitMapping_DepartmentID] ON [dbo].[DepartmentDayUnitMapping]
(
	[DepartmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_DepartmentDayUnitMapping_UnitID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_DepartmentDayUnitMapping_UnitID] ON [dbo].[DepartmentDayUnitMapping]
(
	[UnitID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_District_StateID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_District_StateID] ON [dbo].[District]
(
	[StateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Mandal_DistrictID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_Mandal_DistrictID] ON [dbo].[Mandal]
(
	[DistrictID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_OPRegistration_DepartmentID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_OPRegistration_DepartmentID] ON [dbo].[OPRegistration]
(
	[DepartmentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_OPRegistration_FeeTypeID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_OPRegistration_FeeTypeID] ON [dbo].[OPRegistration]
(
	[FeeTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_OPRegistration_PatientID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_OPRegistration_PatientID] ON [dbo].[OPRegistration]
(
	[PatientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_OPRegistration_SpecialityID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_OPRegistration_SpecialityID] ON [dbo].[OPRegistration]
(
	[SpecialityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Patient_AgeTypeID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_Patient_AgeTypeID] ON [dbo].[Patient]
(
	[AgeTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Patient_BloodGroupID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_Patient_BloodGroupID] ON [dbo].[Patient]
(
	[BloodGroupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Patient_GenderID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_Patient_GenderID] ON [dbo].[Patient]
(
	[GenderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Patient_IDProofTypeID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_Patient_IDProofTypeID] ON [dbo].[Patient]
(
	[IDProofTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Patient_MaritalStatusID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_Patient_MaritalStatusID] ON [dbo].[Patient]
(
	[MaritalStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Patient_PatientTypeID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_Patient_PatientTypeID] ON [dbo].[Patient]
(
	[PatientTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Patient_PrefixID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_Patient_PrefixID] ON [dbo].[Patient]
(
	[PrefixID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Patient_ReligionID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_Patient_ReligionID] ON [dbo].[Patient]
(
	[ReligionID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Patient_VillageID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_Patient_VillageID] ON [dbo].[Patient]
(
	[VillageID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_PatientAddress_PatientID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_PatientAddress_PatientID] ON [dbo].[PatientAddress]
(
	[PatientID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Prefix_GenderID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_Prefix_GenderID] ON [dbo].[Prefix]
(
	[GenderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_UnitDoctorMapping_DoctorID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_UnitDoctorMapping_DoctorID] ON [dbo].[UnitDoctorMapping]
(
	[DoctorID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_UnitDoctorMapping_UnitID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_UnitDoctorMapping_UnitID] ON [dbo].[UnitDoctorMapping]
(
	[UnitID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Village_MandalID]    Script Date: 05-09-2024 09:13:24 ******/
CREATE NONCLUSTERED INDEX [IX_Village_MandalID] ON [dbo].[Village]
(
	[MandalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AspNetRoleClaims]  WITH CHECK ADD  CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId] FOREIGN KEY([RoleId])
REFERENCES [dbo].[AspNetRoles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetRoleClaims] CHECK CONSTRAINT [FK_AspNetRoleClaims_AspNetRoles_RoleId]
GO
ALTER TABLE [dbo].[AspNetUserClaims]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserClaims] CHECK CONSTRAINT [FK_AspNetUserClaims_AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[AspNetUserLogins]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserLogins] CHECK CONSTRAINT [FK_AspNetUserLogins_AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId] FOREIGN KEY([RoleId])
REFERENCES [dbo].[AspNetRoles] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_AspNetUserRoles_AspNetRoles_RoleId]
GO
ALTER TABLE [dbo].[AspNetUserRoles]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserRoles] CHECK CONSTRAINT [FK_AspNetUserRoles_AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[AspNetUserTokens]  WITH CHECK ADD  CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[AspNetUsers] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AspNetUserTokens] CHECK CONSTRAINT [FK_AspNetUserTokens_AspNetUsers_UserId]
GO
ALTER TABLE [dbo].[DepartmentDayUnitMapping]  WITH CHECK ADD  CONSTRAINT [FK_DepartmentDayUnitMapping_Day_DayID] FOREIGN KEY([DayID])
REFERENCES [dbo].[DaywiseSchedule] ([DayID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DepartmentDayUnitMapping] CHECK CONSTRAINT [FK_DepartmentDayUnitMapping_Day_DayID]
GO
ALTER TABLE [dbo].[DepartmentDayUnitMapping]  WITH CHECK ADD  CONSTRAINT [FK_DepartmentDayUnitMapping_Department_DepartmentID] FOREIGN KEY([DepartmentID])
REFERENCES [dbo].[Department] ([DepartmentID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DepartmentDayUnitMapping] CHECK CONSTRAINT [FK_DepartmentDayUnitMapping_Department_DepartmentID]
GO
ALTER TABLE [dbo].[DepartmentDayUnitMapping]  WITH CHECK ADD  CONSTRAINT [FK_DepartmentDayUnitMapping_Unit_UnitID] FOREIGN KEY([UnitID])
REFERENCES [dbo].[Unit] ([UnitID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[DepartmentDayUnitMapping] CHECK CONSTRAINT [FK_DepartmentDayUnitMapping_Unit_UnitID]
GO
ALTER TABLE [dbo].[District]  WITH CHECK ADD  CONSTRAINT [FK_District_State_StateID] FOREIGN KEY([StateID])
REFERENCES [dbo].[State] ([StateID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[District] CHECK CONSTRAINT [FK_District_State_StateID]
GO
ALTER TABLE [dbo].[Mandal]  WITH CHECK ADD  CONSTRAINT [FK_Mandal_District_DistrictID] FOREIGN KEY([DistrictID])
REFERENCES [dbo].[District] ([DistrictID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Mandal] CHECK CONSTRAINT [FK_Mandal_District_DistrictID]
GO
ALTER TABLE [dbo].[OPRegistration]  WITH CHECK ADD  CONSTRAINT [FK_OPRegistration_Department_DepartmentID] FOREIGN KEY([DepartmentID])
REFERENCES [dbo].[Department] ([DepartmentID])
GO
ALTER TABLE [dbo].[OPRegistration] CHECK CONSTRAINT [FK_OPRegistration_Department_DepartmentID]
GO
ALTER TABLE [dbo].[OPRegistration]  WITH CHECK ADD  CONSTRAINT [FK_OPRegistration_Doctor] FOREIGN KEY([DoctorID])
REFERENCES [dbo].[Doctor] ([DoctorID])
GO
ALTER TABLE [dbo].[OPRegistration] CHECK CONSTRAINT [FK_OPRegistration_Doctor]
GO
ALTER TABLE [dbo].[OPRegistration]  WITH CHECK ADD  CONSTRAINT [FK_OPRegistration_FeeType_FeeTypeID] FOREIGN KEY([FeeTypeID])
REFERENCES [dbo].[FeeType] ([FeeTypeID])
GO
ALTER TABLE [dbo].[OPRegistration] CHECK CONSTRAINT [FK_OPRegistration_FeeType_FeeTypeID]
GO
ALTER TABLE [dbo].[OPRegistration]  WITH CHECK ADD  CONSTRAINT [FK_OPRegistration_Patient_PatientID] FOREIGN KEY([PatientID])
REFERENCES [dbo].[Patient] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[OPRegistration] CHECK CONSTRAINT [FK_OPRegistration_Patient_PatientID]
GO
ALTER TABLE [dbo].[OPRegistration]  WITH CHECK ADD  CONSTRAINT [FK_OPRegistration_Speciality_SpecialityID] FOREIGN KEY([SpecialityID])
REFERENCES [dbo].[Speciality] ([SpecialityID])
GO
ALTER TABLE [dbo].[OPRegistration] CHECK CONSTRAINT [FK_OPRegistration_Speciality_SpecialityID]
GO
ALTER TABLE [dbo].[Patient]  WITH CHECK ADD  CONSTRAINT [FK_Patient_AgeType_AgeTypeID] FOREIGN KEY([AgeTypeID])
REFERENCES [dbo].[AgeType] ([AgeTypeID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Patient] CHECK CONSTRAINT [FK_Patient_AgeType_AgeTypeID]
GO
ALTER TABLE [dbo].[Patient]  WITH CHECK ADD  CONSTRAINT [FK_Patient_BloodGroup_BloodGroupID] FOREIGN KEY([BloodGroupID])
REFERENCES [dbo].[BloodGroup] ([BloodGroupID])
GO
ALTER TABLE [dbo].[Patient] CHECK CONSTRAINT [FK_Patient_BloodGroup_BloodGroupID]
GO
ALTER TABLE [dbo].[Patient]  WITH CHECK ADD  CONSTRAINT [FK_Patient_Gender_GenderID] FOREIGN KEY([GenderID])
REFERENCES [dbo].[Gender] ([GenderID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Patient] CHECK CONSTRAINT [FK_Patient_Gender_GenderID]
GO
ALTER TABLE [dbo].[Patient]  WITH CHECK ADD  CONSTRAINT [FK_Patient_IDProofType_IDProofTypeID] FOREIGN KEY([IDProofTypeID])
REFERENCES [dbo].[IDProofType] ([IDProofTypeID])
GO
ALTER TABLE [dbo].[Patient] CHECK CONSTRAINT [FK_Patient_IDProofType_IDProofTypeID]
GO
ALTER TABLE [dbo].[Patient]  WITH CHECK ADD  CONSTRAINT [FK_Patient_MaritalStatus_MaritalStatusID] FOREIGN KEY([MaritalStatusID])
REFERENCES [dbo].[MaritalStatus] ([MaritalStatusID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Patient] CHECK CONSTRAINT [FK_Patient_MaritalStatus_MaritalStatusID]
GO
ALTER TABLE [dbo].[Patient]  WITH CHECK ADD  CONSTRAINT [FK_Patient_PatientType_PatientTypeID] FOREIGN KEY([PatientTypeID])
REFERENCES [dbo].[PatientType] ([PatientTypeID])
GO
ALTER TABLE [dbo].[Patient] CHECK CONSTRAINT [FK_Patient_PatientType_PatientTypeID]
GO
ALTER TABLE [dbo].[Patient]  WITH CHECK ADD  CONSTRAINT [FK_Patient_Prefix_PrefixID] FOREIGN KEY([PrefixID])
REFERENCES [dbo].[Prefix] ([PrefixID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Patient] CHECK CONSTRAINT [FK_Patient_Prefix_PrefixID]
GO
ALTER TABLE [dbo].[Patient]  WITH CHECK ADD  CONSTRAINT [FK_Patient_Religion_ReligionID] FOREIGN KEY([ReligionID])
REFERENCES [dbo].[Religion] ([ReligionID])
GO
ALTER TABLE [dbo].[Patient] CHECK CONSTRAINT [FK_Patient_Religion_ReligionID]
GO
ALTER TABLE [dbo].[Patient]  WITH CHECK ADD  CONSTRAINT [FK_Patient_Village_VillageID] FOREIGN KEY([VillageID])
REFERENCES [dbo].[Village] ([VillageID])
GO
ALTER TABLE [dbo].[Patient] CHECK CONSTRAINT [FK_Patient_Village_VillageID]
GO
ALTER TABLE [dbo].[PatientAddress]  WITH CHECK ADD  CONSTRAINT [FK_PatientAddress_Patient_PatientID] FOREIGN KEY([PatientID])
REFERENCES [dbo].[Patient] ([ID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[PatientAddress] CHECK CONSTRAINT [FK_PatientAddress_Patient_PatientID]
GO
ALTER TABLE [dbo].[Prefix]  WITH CHECK ADD  CONSTRAINT [FK_Prefix_Gender_GenderID] FOREIGN KEY([GenderID])
REFERENCES [dbo].[Gender] ([GenderID])
GO
ALTER TABLE [dbo].[Prefix] CHECK CONSTRAINT [FK_Prefix_Gender_GenderID]
GO
ALTER TABLE [dbo].[UnitDoctorMapping]  WITH CHECK ADD  CONSTRAINT [FK_UnitDoctorMapping_Doctor_DoctorID] FOREIGN KEY([DoctorID])
REFERENCES [dbo].[Doctor] ([DoctorID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UnitDoctorMapping] CHECK CONSTRAINT [FK_UnitDoctorMapping_Doctor_DoctorID]
GO
ALTER TABLE [dbo].[UnitDoctorMapping]  WITH CHECK ADD  CONSTRAINT [FK_UnitDoctorMapping_Unit_UnitID] FOREIGN KEY([UnitID])
REFERENCES [dbo].[Unit] ([UnitID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UnitDoctorMapping] CHECK CONSTRAINT [FK_UnitDoctorMapping_Unit_UnitID]
GO
ALTER TABLE [dbo].[Village]  WITH CHECK ADD  CONSTRAINT [FK_Village_Mandal_MandalID] FOREIGN KEY([MandalID])
REFERENCES [dbo].[Mandal] ([MandalID])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Village] CHECK CONSTRAINT [FK_Village_Mandal_MandalID]
GO
/****** Object:  StoredProcedure [dbo].[GenerateOPIDList]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[GenerateOPIDList]
    @numIDs INT,               -- Number of OPIDs to generate
    @result NVARCHAR(MAX) OUTPUT -- Output parameter for the comma-separated list of OPIDs
AS
BEGIN
    -- Declare variables for OPID generation
    DECLARE @datePrefix NVARCHAR(8);   -- To store the date prefix for OPID
    DECLARE @formattedId NVARCHAR(4);  -- To store the formatted sequence number
    DECLARE @startSequence INT = 1;    -- Starting sequence number
    DECLARE @currentDate DATE = CAST(GETDATE() AS DATE);  -- Current date
    DECLARE @opID NVARCHAR(13);        -- To store the generated OPID

    -- Initialize the result variable
    SET @result = '';

    -- Set the date prefix for OPID in yyMMdd format
    SET @datePrefix = FORMAT(@currentDate, 'yyMMdd');

    -- Loop through the range of sequence numbers to generate the OPIDs
    WHILE @startSequence <= @numIDs
    BEGIN
        -- Format the sequence number with leading zeros (4 digits)
        SET @formattedId = RIGHT('0000' + CAST(@startSequence AS VARCHAR(4)), 4);
        
        -- Generate the OPID
        SET @opID = 'OP.' + @datePrefix + @formattedId;
        
        -- Append the generated OPID to the result, followed by a comma
        SET @result = @result + @opID + ',';
        
        -- Increment the sequence number
        SET @startSequence = @startSequence + 1;
    END

    -- Remove the trailing comma from the result
    SET @result = LEFT(@result, LEN(@result) - 1);

    -- Output the result
    SELECT @result AS OPIDs;
END;
GO
/****** Object:  StoredProcedure [dbo].[GetUHIDAndOPID]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE   PROCEDURE [dbo].[GetUHIDAndOPID]
AS
BEGIN
    -- Declare variables for UHID and OPID generation
    DECLARE @datePrefix NVARCHAR(8);   -- To store the date prefix for UHID and OPID
    DECLARE @nextId INT;               -- To store the next sequence number
    DECLARE @formattedId NVARCHAR(4);  -- To store the formatted sequence number
    DECLARE @uhID NVARCHAR(12);        -- To store the generated UHID
    DECLARE @opID NVARCHAR(13);        -- To store the generated OPID (length adjusted to account for appended '1')

    -- Get today's date
    DECLARE @tomorrowDate DATE = GETDATE();

    -- Set the date prefix for UHID in yyyyMMdd format
    SET @datePrefix = FORMAT(@tomorrowDate, 'yyyyMMdd');

    -- Calculate the next sequence number for UHID
    -- Extract the numeric part of UHID after the date prefix
    SELECT @nextId = ISNULL(MAX(CAST(SUBSTRING(UHID, LEN(@datePrefix) + 1, LEN(UHID) - LEN(@datePrefix)) AS INT)), 0) + 1
    FROM Patient
    WHERE UHID LIKE @datePrefix + '%';

    -- Format the UHID with zero-padding (4 digits for sequence part)
    SET @formattedId = RIGHT('0000' + CAST(@nextId AS VARCHAR(4)), 4);
    SET @uhID = @datePrefix + @formattedId;

    -- Set the date prefix for OPID in yyMMdd format
    SET @datePrefix = FORMAT(@tomorrowDate, 'yyMMdd');

    -- Generate OPID and append '1' at the end
    SET @opID = 'OP.' + @datePrefix + @formattedId + '1';

    -- Output the results
    SELECT @opID AS OPID, GETDATE() AS VisitDate;
END;

--EXEC GetUHIDAndOPID


GO
/****** Object:  StoredProcedure [dbo].[InsertOPRegistration]    Script Date: 05-09-2024 09:13:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[InsertOPRegistration]
    @PatientID INT,
    @OPID NVARCHAR(20),
    @VisitDate DATETIME,
    @IsMlcCase BIT = NULL,
    @IsEmergencyCase BIT = NULL,
    @DepartmentID INT = NULL,
	@DoctorID INT = NULL,
    @SpecialityID INT = NULL,   
    @FeeTypeID INT = NULL,
    @ReferredBy NVARCHAR(50),
    @CreatedDate DATETIME = NULL,
    @IsActive BIT
AS
BEGIN
    -- Use TRY-CATCH to handle potential errors
    BEGIN TRY
        -- Insert into OPRegistration table
        INSERT INTO OPRegistration (
            PatientID,
            OPID,
            VisitDate,
            IsMlcCase,
            IsEmergencyCase,
            DepartmentID,
			DoctorID,
            SpecialityID,           
            FeeTypeID,
            ReferredBy,
            CreatedDate,
            IsActive
        )
        VALUES (
            @PatientID,
            @OPID,
            @VisitDate,
            @IsMlcCase,
            @IsEmergencyCase,
            @DepartmentID,
			@DoctorID,
            @SpecialityID,           
            @FeeTypeID,
            @ReferredBy,
            @CreatedDate,
            @IsActive
        );

        -- Optional: Return the ID of the inserted record (if you have an identity column)
        SELECT SCOPE_IDENTITY() AS NewID;
    END TRY
    BEGIN CATCH
        -- Handle errors here (log them, rethrow them, etc.)
        THROW;
    END CATCH
END
GO
USE [master]
GO
ALTER DATABASE [DDLAutomationProcess] SET  READ_WRITE 
GO
